format = """
$directory\
$git_branch\
$git_status\
$all\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold #a3be8c)" 
error_symbol = "[❯](bold #bf616a)"

[directory]
style = "bold #81a1c1"
