[main]
font=JetBrains Mono:size=14
prompt="> "
terminal=ghostty
width=40
horizontal-pad=25
vertical-pad=15
inner-pad=8
line-height=25

[colors]
# Black with 85% transparency (D9 in hex)
background=000000d9
text=eeeeeeff
match=ffffffff
selection=333333ff
selection-text=ffffffff
selection-match=ffffffff
# White border with 30% transparency (4D in hex)
border=ffffff4d

[border]
width=2
radius=15
